---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(ggrepel)

```

```{r Get count matrix}
setwd("/stor/work/Brock/Tyler/optimalSeparation/notebooks/separation")
cts = read.csv('../../data/tagSeqOuts/star_salmon/salmon.merged.gene_counts.tsv', sep = '\t', row.names = 1)
cts = cts[,2:ncol(cts)]
cts = round(cts)

colKeep436 = c("G1.MB435BST2lo",  "G2.MB435BST2lo",  "G3.MB435BST2lo",  "H1.MB435BST2hi",  "H2.MB435BST2hi",  "H3.MB435BST2hi")
colKeep231 = c("C1.MB231ESAMneg", "C2.MB231ESAMneg",  "C3.MB231ESAMneg", "D1.MB231ESAMpos", "D2.MB231ESAMpos", "D3.MB231ESAMpos")
colKeep = c(colKeep436, colKeep231)
cts = cts[,colKeep]

cts231 = cts[,colKeep231]
cts436 = cts[,colKeep436]

dfGenes436 = read.csv('../../data/topGenes436.csv', row.names = 1)
dfGenes231 = read.csv('../../data/topGenes231.csv', row.names = 1)
```

```{r}
cts436Low = cts[,c("G1.MB435BST2lo",  "G2.MB435BST2lo",  "G3.MB435BST2lo")]
cts436High = cts[,c("H1.MB435BST2hi",  "H2.MB435BST2hi",  "H3.MB435BST2hi")]
cts231Low = cts[,c("C1.MB231ESAMneg", "C2.MB231ESAMneg",  "C3.MB231ESAMneg")]
cts231High = cts[,c("D1.MB231ESAMpos", "D2.MB231ESAMpos", "D3.MB231ESAMpos")]

# write.csv(cts231Low, '/stor/scratch/Brock/Tyler/geoUpload/tagSeq/processed/cts231Low.csv')
# write.csv(cts231High, '/stor/scratch/Brock/Tyler/geoUpload/tagSeq/processed/cts231High.csv')
# write.csv(cts436Low, '/stor/scratch/Brock/Tyler/geoUpload/tagSeq/processed/cts436Low.csv')
# write.csv(cts436High, '/stor/scratch/Brock/Tyler/geoUpload/tagSeq/processed/cts436High.csv')
```

```{r Generate DE Genes}
conditions = c('low', 'low', 'low', 'high', 'high', 'high')
types = rep('paired-end', 6)
coldata231 = data.frame(condition = conditions, type = types)
row.names(coldata231) = colnames(cts231)

coldata436 = data.frame(condition = conditions, type = types)
row.names(coldata436) = colnames(cts436)

dds231 <- DESeqDataSetFromMatrix(countData = cts231,
                              colData = coldata231,
                              design = ~ condition)
dds231 <- DESeq(dds231)
res231 <- results(dds231, contrast = c('condition', 'high', 'low'))

dds436 <- DESeqDataSetFromMatrix(countData = cts436,
                              colData = coldata436,
                              design = ~ condition)
dds436 <- DESeq(dds436)
res436 <- results(dds436, contrast = c('condition', 'high', 'low'))
```
```{r}
conditions = c('low', 'low', 'low', 'high', 'high', 'high')
types = rep('paired-end', 6)
coldata231 = data.frame(condition = conditions, type = types)
row.names(coldata231) = colnames(cts231)

coldata436 = data.frame(condition = conditions, type = types)
row.names(coldata436) = colnames(cts436)

dds231 <- DESeqDataSetFromMatrix(countData = cts231,
                              colData = coldata231,
                              design = ~ condition)
dds231 <- DESeq(dds231)
res1 <- data.frame(results(dds231,contrast = c('condition', 'high', 'low')))
res2 <- data.frame(results(dds231, contrast = c('condition', 'low', 'high')))

```

```{r}
nTopGenes = 200
nLower = dim(dfGenes436)[1]-nTopGenes+1
highGenes = dfGenes436$names[1:nTopGenes]
lowGenes = dfGenes436$names[nLower:dim(dfGenes436)[1]]
topGenes436 = c(highGenes, lowGenes)

norm436 = data.frame(counts(dds436, normalized = TRUE))
top436 = norm436[topGenes436,]
# top436 =cts436[c('BST2', 'ESAM'),]
top436 = top436[complete.cases(top436),]
top436 = top436[rowSums(top436) > 0,]

# Reverse order of samples such that it's BST2High and then low 
# top436 = rev(top436)

acceptedSingleCell = dfGenes436[dfGenes436$names %in% row.names(top436),]

nLow = sum(acceptedSingleCell$score > 0)
nHigh = sum(acceptedSingleCell$score < 0)

labelRows = data.frame(group = as.factor(c(rep('BST2 Low', nLow), rep('BST2 High', nHigh))))

colnames(labelRows) = 'Subpopulation'
rownames(labelRows) = rownames(top436)


labelCols = data.frame(group = as.factor(c(rep('BST2 High', 3), rep('BST2 Low', 3))))
rownames(labelCols) = colnames(top436)

matColors = list(Subpopulation = c('BST2 High' = '#44B1BB', 'BST2 Low' = '#BB4E44'))

# matColors = list(Subpopulation = c('1' = '#44B1BB', '2' = '#BB4E44'))
p = pheatmap(
              top436, 
              scale = 'row',
              treeheight_row = 0, 
              treeheight_col = 15,
              # annotation_col = labelCols,
              annotation_row = labelRows,
              annotation_legend = FALSE, 
              annotation_colors = matColors,
              annotation_names_row = FALSE,
              annotation_names_col = FALSE,
              drop_levels = TRUE,
              cluster_rows = FALSE,
              # legend = FALSE,
              labels_row = rep('',dim(top436)[1]),
              labels_col = rep('',dim(top436)[2]),
              angle_col = 0
)
scaling = 2

ggsave('../../figures/final/436TagSeqHeatmap.png',
       p,
       dpi = 900,
       height = 2.4*scaling,
       width = 2.2*scaling)
```

```{r}
nTopGenes = 200
nLower = dim(dfGenes231)[1]-nTopGenes+1
highGenes = dfGenes231$names[1:nTopGenes]
lowGenes = dfGenes231$names[nLower:dim(dfGenes231)[1]]
topGenes231 = c(highGenes, lowGenes)

norm231 = data.frame(counts(dds231, normalized = TRUE))
top231 = norm231[topGenes231,]
# top231 =cts231[c('BST2', 'ESAM'),]
top231 = top231[complete.cases(top231),]
top231 = top231[rowSums(top231) > 0,]

acceptedSingleCell = dfGenes231[dfGenes231$names %in% row.names(top231),]
# Reverse order of samples such that it's BST2High and then low 
# top231 = rev(top231)

nLow = sum(acceptedSingleCell$score > 0)
nHigh = sum(acceptedSingleCell$score < 0)

labelRows = data.frame(group = as.factor(c(rep('ESAM Low', nLow), rep('ESAM High', nHigh))))

colnames(labelRows) = 'Subpopulation'
rownames(labelRows) = rownames(top231)

labelCols = data.frame(group = as.factor(c(rep('ESAM High', 3), rep('ESAM Low', 3))))
rownames(labelCols) = colnames(top231)

matColors = list(Subpopulation = c('ESAM High' = '#44B1BB', 'ESAM Low' = '#BB4E44'))

# matColors = list(Subpopulation = c('1' = '#44B1BB', '2' = '#BB4E44'))
p = pheatmap(
              top231, 
              scale = 'row',
              treeheight_row = 0, 
              treeheight_col = 15,
              # annotation_col = labelCols,
              annotation_row = labelRows,
              annotation_legend = FALSE, 
              annotation_colors = matColors,
              annotation_names_row = FALSE,
              annotation_names_col = FALSE,
              drop_levels = TRUE,
              cluster_rows = FALSE,
              # legend = FALSE,
              labels_row = rep('',dim(top231)[1]),
              labels_col = rep('',dim(top231)[2]),
              angle_col = 0
)
scaling = 2

ggsave('../../figures/final/231TagSeqHeatmap.png',
       p,
       dpi = 900,
       height = 2.4*scaling,
       width = 2.2*scaling)

```

```{r}

emdGenes = read.csv('../../data/optimalGenes/allEMDGenesNewOld.csv', row.names = 1)
emdGenes436 = emdGenes[emdGenes$cellLine == 'mdamb436',]
emdGenes231 = emdGenes[emdGenes$cellLine == 'mdamb231',]

# topEMD436 = emdGenes436$genes[0:10]
# topEMD231 = emdGenes231$genes[0:10]
head(emdGenes436)

row.names(emdGenes436) = seq(1, dim(emdGenes436)[1])
row.names(emdGenes231) = seq(1, dim(emdGenes231)[1])

emdGenes436 = emdGenes436[,2:3]
emdGenes231 = emdGenes231[,2:3]

colnames(emdGenes436) = c('genes', 'score')
colnames(emdGenes231) = c('genes', 'score')

write.csv(emdGenes436, '../../data/emdGenesRankScore436.csv')
write.csv(emdGenes231, '../../data/emdGenesRankScore231.csv')

```

```{r}
# plot_DE_volcano_genelist <- function(res, title, padj_threshold = 0.05, abs_l2fc_min = 1, colrs=c('red','forestgreen'))
padj = 0.05
l2fc = 1
res = data.frame(res231)
cols = c('#BB4E44', '#44B1BB')
plotVolc <- res %>% select(log2FoldChange, pvalue, padj) %>% rownames_to_column('gene')
plotVolc = plotVolc[complete.cases(plotVolc),]
sigDown = plotVolc$log2FoldChange < -l2fc & plotVolc$padj < padj
sigUp   = plotVolc$log2FoldChange >  l2fc & plotVolc$padj < padj
plotVolc$color = 'NA'
plotVolc$color[sigDown] = 'down'
plotVolc$color[sigUp] = 'up'
cols = c('NA' = 'gray', 'down' = cols[1], 'up' = cols[2])

topEMD231 = emdGenes231$genes[emdGenes231$genes %in% plotVolc$gene][0:10]

plotVolc$geneLabel = ''
plotVolc$geneLabel[plotVolc$gene %in% topEMD231] = plotVolc$gene[plotVolc$gene %in% topEMD231]

xticks = round(seq(min(plotVolc$log2FoldChange), max(plotVolc$log2FoldChange)))
p = ggplot(plotVolc, aes(x = log2FoldChange, y = -log10(padj), label = geneLabel))+
  geom_point(aes(color = factor(color)), size = 0.4)+
  scale_color_manual(values = cols)+
  geom_vline(xintercept = c(-l2fc,l2fc), linewidth=0.1, linetype='dashed') +
  geom_hline(yintercept = c(-log10(padj)), linewidth=0.1, linetype='dashed') +
  scale_x_continuous(breaks = xticks) + 
  theme_few()+
  geom_text_repel(max.overlaps = Inf, max.iter = 10000, min.segment.length = 0, force = 200, size = 2, segment.size=.25, bg.color = 'white')+
  labs(title = '') + 
  theme(legend.position = "none", text = element_text(size = 10))
print(p)
ggsave('../../figures/final/231VolcanoPlot.png', p, dpi = 500, width = 3.3, height = 1.9)

```

```{r}
padj = 0.05
l2fc = 1
res = data.frame(res436)
cols = c('#BB4E44', '#44B1BB')
plotVolc <- res %>% select(log2FoldChange, pvalue, padj) %>% rownames_to_column('gene')
plotVolc = plotVolc[complete.cases(plotVolc),]
sigDown = plotVolc$log2FoldChange < -l2fc & plotVolc$padj < padj
sigUp   = plotVolc$log2FoldChange >  l2fc & plotVolc$padj < padj
plotVolc$color = 'NA'
plotVolc$color[sigDown] = 'down'
plotVolc$color[sigUp] = 'up'
cols = c('NA' = 'gray', 'down' = cols[1], 'up' = cols[2])

topEMD436 = emdGenes436$genes[emdGenes436$genes %in% plotVolc$gene][0:10]

plotVolc$geneLabel = ''
plotVolc$geneLabel[plotVolc$gene %in% topEMD436] = plotVolc$gene[plotVolc$gene %in% topEMD436]

xticks = round(seq(min(plotVolc$log2FoldChange), max(plotVolc$log2FoldChange)))
p = ggplot(plotVolc, aes(x = log2FoldChange, y = -log10(padj), label = geneLabel))+
  geom_point(aes(color = factor(color)), size = 0.4)+
  scale_color_manual(values = cols)+
  geom_vline(xintercept = c(-l2fc,l2fc), linewidth=0.1, linetype='dashed') +
  geom_hline(yintercept = c(-log10(padj)), linewidth=0.1, linetype='dashed') +
  scale_x_continuous(breaks = xticks) + 
  theme_few()+
  geom_text_repel(max.overlaps = Inf, max.iter = 10000, min.segment.length = 0, force = 200, size = 2, segment.size=.25, bg.color = 'white')+
  labs(title = '') + 
  theme(legend.position = "none", text = element_text(size = 10))

ggsave('../../figures/final/436VolcanoPlot.png',  p, dpi = 500, width = 3.3, height = 1.9)

```

```{r}
# Get significant tag seq genes
sig231Tag = data.frame(res231)
sig231Tag = sig231Tag[complete.cases(sig231Tag),]
sig231Tag = sig231Tag[sig231Tag$padj<0.05,]
sc231 = dfGenes231
rownames(sc231) = sc231$names
sc231 = sc231[,2:dim(sc231)[2]]

# Make sure we're only comparing genes found in significant tag seq and any scRNA seq
sharedGenes = intersect(rownames(sc231), rownames(sig231Tag))
sig231Tag = sig231Tag[sharedGenes,]
sc231 = sc231[sharedGenes,]

nTop = 100
scESAMPos = sc231[sc231$logfoldchanges > 0,]
scESAMNeg = sc231[sc231$logfoldchanges < 0,]
# Find how many DE tag seq are DE in single cell (same cluster)
# ESAM Pos have logFC > 0
topTagESAMPos = sig231Tag[sig231Tag$log2FoldChange > 0 & sig231Tag$padj < 0.05,]
topTagESAMPos = topTagESAMPos[order(topTagESAMPos$padj, decreasing = FALSE),]
topTagESAMPosGenes = rownames(topTagESAMPos)[0:nTop]
pvals = scESAMPos[topTagESAMPosGenes,'pvals_adj']
pvals = pvals[complete.cases(pvals)]
nSig = sum(pvals < 0.05)
sprintf('%g/%g DE Tag seq ESAM positive genes are significant in matched cluster single cell data', nSig, nTop)

topTagESAMNeg = sig231Tag[sig231Tag$log2FoldChange < 0 & sig231Tag$padj < 0.05,]
topTagESAMNeg = topTagESAMNeg[order(topTagESAMNeg$padj, decreasing = FALSE),]
topTagESAMNegGenes = rownames(topTagESAMNeg)[0:nTop]
pvals = scESAMNeg[topTagESAMNegGenes,'pvals_adj']
pvals = pvals[complete.cases(pvals)]
nSig = sum(pvals < 0.05)
sprintf('%g/%g DE Tag seq ESAM negative genes are significant in matched cluster single cell data', nSig, nTop)

# Find how many DE tag seq are DE in single cell (opposite cluster)
pvals = scESAMNeg[topTagESAMPosGenes,'pvals_adj']
pvals = pvals[complete.cases(pvals)]
nSig = sum(pvals < 0.05)
sprintf('%g/%g DE Tag seq ESAM positive genes are significant in non-matched cluster single cell data', nSig, nTop)

pvals = scESAMPos[topTagESAMNegGenes,'pvals_adj']
pvals = pvals[complete.cases(pvals)]
nSig = sum(pvals < 0.05)
sprintf('%g/%g DE Tag seq ESAM negative genes are significant in non-matched cluster single cell data', nSig, nTop)

```

```{r}
# Get significant tag seq genes
sig436Tag = data.frame(res436)
sig436Tag = sig436Tag[complete.cases(sig436Tag),]
sig436Tag = sig436Tag[sig436Tag$padj<0.05,]
sc436 = dfGenes436
rownames(sc436) = sc436$names
sc436 = sc436[,2:dim(sc436)[2]]

# Make sure we're only comparing genes found in significant tag seq and any scRNA seq
sharedGenes = intersect(rownames(sc436), rownames(sig436Tag))
sig436Tag = sig436Tag[sharedGenes,]
sc436 = sc436[sharedGenes,]

nTop = 100
# BST2 Pos have logFC > 0
scBST2Pos = sc436[sc436$logfoldchanges > 0,]
scBST2Neg = sc436[sc436$logfoldchanges < 0,]

topTagBST2Pos = sig436Tag[sig436Tag$log2FoldChange > 0 & sig436Tag$padj < 0.05,]
topTagBST2Pos = topTagBST2Pos[order(topTagBST2Pos$padj, decreasing = FALSE),]
topTagBST2PosGenes = rownames(topTagBST2Pos)[0:nTop]
pvals = scBST2Pos[topTagBST2PosGenes,'pvals_adj']
pvals = pvals[complete.cases(pvals)]
nSig = sum(pvals < 0.05)
sprintf('%g/%g DE Tag seq BST2 positive genes are significant in single cell data', nSig, nTop)

topTagBST2Neg = sig436Tag[sig436Tag$log2FoldChange < 0 & sig436Tag$padj < 0.05,]
topTagBST2Neg = topTagBST2Neg[order(topTagBST2Neg$padj, decreasing = FALSE),]
topTagBST2NegGenes = rownames(topTagBST2Neg)[0:nTop]
pvals = scBST2Neg[topTagBST2NegGenes,'pvals_adj']
pvals = pvals[complete.cases(pvals)]
nSig = sum(pvals < 0.05)
sprintf('%g/%g DE Tag seq BST2 negative genes are significant in single cell data', nSig, nTop)
```
