```{r}
require(sc2marker)
require(Seurat)
require(SeuratWrappers)
```

```{r}
seu231 = readRDS('../../data/toSeurat/231jostnerProcessed.rds')
seu436 = readRDS('../../data/toSeurat/436jostnerProcessed.rds')

```

```{r}
seu231 <- FindNeighbors(seu231, dims = 1:10)
seu231 <- FindClusters(seu231, resolution = 0.05)

seu436 <- FindNeighbors(seu436, dims = 1:10)
seu436 <- FindClusters(seu436, resolution = 0.05)
```

```{r}
DimPlot(seu231, reduction = "umap")
```

```{r}
DimPlot(seu436, reduction = "umap")

```

```{r}
```

```{r}
markers231 = Detect_single_marker(seu231, id = '1', category='Flow', org = 'Human', self.db = './sc2MarkerGenes.csv')
head(markers231, 10)

markers231$rankingc2Marker = seq(1, dim(markers231)[1])
write.csv(markers231, '../../data/toSeurat/231sc2Marker.csv')
```

```{r}
markers436 = Detect_single_marker(seu436, id = '1', category='Flow', org = 'Human', self.db = './sc2MarkerGenes.csv' )
head(markers436, 10)

markers436$rankingsc2Marker = seq(1, dim(markers436)[1])
write.csv(markers436, '../../data/toSeurat/436sc2Marker.csv')
```

```{r}
markersEMD = read.csv('../../data/optimalGenes/allEMDGenesNewOld.csv', row.names = 1)
markersEMD231 = subset(markersEMD, cellLine == 'mdamb231')
markersEMD436 = subset(markersEMD, cellLine == 'mdamb436')

rownames(markersEMD231) = NULL
rownames(markersEMD436) = NULL

markersEMD231$rankingEMD = seq(1, dim(markersEMD231)[1])
markersEMD436$rankingEMD = seq(1, dim(markersEMD436)[1])

colnames(markersEMD231)[2] = 'gene'
colnames(markersEMD436)[2] = 'gene'
```

```{r}
allRankings = 

```